input("Let's play Madlibs!")
going = input("How's it going?")
print(f"Well im doing {going} too")
name = input("What is your name?")
print(f"Hello {name}, and welcome to my text messages project")
color = input("What is favorite color?")
print(f"wow that is a really cool color I like {color} too")
pet = input(f"whats your favorite animal?")
print(f"I wish I had a {pet}, it would seem cool to have a {pet}")
area = input(f"What is your favorite store?")
print(f"I go to that {area} all the time")
print(f"-----------------------------------------------------------------------------------")
print(f"-----------------------------------------------------------------------------------")
print(f"Once upon a time a {color} {pet} went down and bought something for {name} at {area}")
print(f"-----------------------------------------------------------------------------------")
print(f"-----------------------------------------------------------------------------------")